frase = str(input('Digite uma frase:'))
frase = frase.replace(' ', '')
frase = frase.replace(',','')
frase = frase.replace('!', '')
frase = frase.replace('.','')
frase = frase.replace('?', '')
up = frase.upper()
sub = up.replace('Á', 'A')
cnt = sub.count('A')
posi = sub.find('A')
posf = sub.rfind('A')
print('Sua frase tem {} A´s \nO primeiro A é a {}° letra \nO ultimo A é a {}° letra'.format(cnt, posi + 1, posf + 1))